info:
  name: products
  type: http
  seq: 8

http:
  method: POST
  url: http://localhost:3001/api/inventory
  body:
    type: json
    data: |-
      {
        "clientId": 1,
        "items": [
          {
            "productId": 1,
            "quantity": 2,
            "unitPrice": 50
          }
        ]
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
